version: '3.8'

volumes:
  static_value:

services:

  db:
    image: postgres:15.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./test_antipoff/.env
    restart: always

  backend:
    image: test_antipoff
    volumes:
      - static_value:/app/static/
    depends_on:
      - db
    env_file:
      - ./test_antipoff/.env
    restart: always

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - backend